### ISSUE TITLE
Some thoughts about the bot framework

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-chatbot-js#1]
I got the ping bot running by following readme.

Some improvement about this process I think would be useful:

- After cloning, default master branch is empty, I have to find the right branch. I know there is a video, but I would like to solve it from text, it would simple and direct, people are lazy, better get it done just from readme, treat video as last resolve.
- Better add `git clone xxx && cd xxx part too`
- I have click two external url to get some info(env file and `/bot/oauth` url), make it less smoother, these info/file better in the readme or an example file, less files in the repo may not mean simple to the user, convinient is more important.
- The database init, I would hope it will be inited by the framework, not by curl, if it can be automattic, let us make it so.

Other thoughts:
- Bot framework could remove express as depedency, it is not relavent enough, user could use any web framework to dev bot, it should not in the main logic.
- Should remove sequenlize too, it is too heavy, bot framework should focus on bot logic, let user decide using what database and the db schema.
- User auth part should in the framework, or at least a extension, after all we should encourage users to use glip and register as ringcentral user.

**Comment by tylerlong** [comment]
Thank you for the feedback @zxdong262 , very helpful!

> After cloning, default master branch is empty

It is not the recommended approach. By design I suppose the user should build everything **from scratch** by **reading** the tutorial instead of **cloning** the tutorial.  

---

> Better add `git clone xxx && cd xxx part too`

I will add `mkdir xxx && cd xxx` since `git clone` is not part of the workflow.

---

> I have click two external url to get some info

I've got your point.  But that means harder to maintain. Every time I update a file I need to sync it to readme. 

---

> The database init, I would hope it will be inited by the framework, not by curl

I like this idea, will investigate

---

> Bot framework could remove express as dependency

I am not an expert of node http server side development. Express is the only node web framework that I have experience with. It is also the most famous one. 

---

> Should remove sequelize too, it is too heavy, bot framework should focus on bot logic, let user decide using what database and the db schema.

Most users don't need to care about db schema at all.  Just [10 lines of code](https://github.com/tylerlong/glip-ping-chatbot/blob/express/express.js) to create a bot.
It might be "heavy", but it's just for me, not for the user.

---

> User auth part should in the framework

Most bots don't need RingCentral data. For example: https://www.ringcentral.com/apps/glip-crontab-chatbot.   And two of your demo bots: date-time-bot, survey-bot.

To Glip, RingCentral data is just one data source, not too different from Google data, GitHub data...etc. I don't want to make it special. I designed a general flow for all these data sources.  I am planning to create a google drive demo bot to show how to handle Google data. (RC Assistant is the demo bot for RingCentral data).
